linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

  disable:
    - errcheck

run:
  timeout: 5m
  skip-dirs:
    - utils

linters-settings:
  gocyclo:
    min-complexity: 16
  govet:
    check-shadowing: false
  lll:
    line-length: 250
  nakedret:
    command: nakedret
    pattern: ^(?P<path>.*?\\.go):(?P<line>\\d+)\\s*(?P<message>.*)$

issues:
  # The default exclusion rules are a bit too permissive, so copying the relevant ones below
  exclude-use-default: false

  exclude:
    - parameter .* always receives

  exclude-rules:
    - text: "G107: Potential HTTP request made with variable url"
      linters:
        - gosec
    - text: "G304: Potential file inclusion via variable"
      linters:
        - gosec
    - text: "composites: `github.com/1azunna/zapgo/internal/docker.Docker` composite literal uses unkeyed fields"
      linters:
        - govet
    - text: "SA5008: duplicate struct tag \"choice\""
      linters:
        - staticcheck