name: Release
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release zapgo Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, darwin/amd64, darwin/arm64
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: GoReleaser
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.17.6.linux-amd64.tar.gz"
        binary_name: "zapgo"
        build_flags: "-tags=${{ github.ref_name }} -v"
        ldflags: "-s -w -X main.version=${{ github.ref_name }} -X main.date=${{ steps.date.outputs.date }}"
