name: Release
on:
  workflow_run:
    workflows: ["golangci-lint"]
    branches: [main]
    types: 
      - completed
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release zapgo Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.24
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.17.6.linux-amd64.tar.gz"
        project_path: "./cmd/zapgo"
        binary_name: "zapgo"